### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by oaksvirals** [Ivorforce/Psychedelicraft#11]
We've been getting server crashes time to time with this report:

"Description: Exception in server tick loop

java.lang.NoClassDefFoundError: net/minecraft/client/resources/I18n
	at ivorius.psychedelicraft.fluids.FluidAlcohol.getLocalizedName(FluidAlcohol.java:290)
	at ivorius.psychedelicraft.crafting.RecipePourDrink.visualCraftingResult(RecipePourDrink.java:45)
	at ivorius.psychedelicraft.crafting.RecipeActionRepresentation.func_77569_a(RecipeActionRepresentation.java:32)
	at net.minecraft.item.crafting.CraftingManager.func_82787_a(CraftingManager.java:363)
	at net.minecraft.inventory.ContainerPlayer.func_75130_a(ContainerPlayer.java:97)
	at net.minecraft.inventory.InventoryCrafting.func_70299_a(InventoryCrafting.java:161)
	at net.minecraft.inventory.Slot.func_75215_d(Slot.java:77)
	at net.minecraft.inventory.Container.func_75144_a(Container.java:408)
	at net.minecraft.network.NetHandlerPlayServer.func_147351_a(NetHandlerPlayServer.java:2043)
	at net.minecraft.network.play.client.C0EPacketClickWindow.func_148833_a(SourceFile:32)
	at net.minecraft.network.play.client.C0EPacketClickWindow.func_148833_a(SourceFile:10)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:980)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.resources.I18n
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 18 more
Caused by: java.lang.NullPointerException"

**Comment by Ivorforce** [comment]
That's been fixed already - try using the latest nightly build.
