### ISSUE TITLE
Crash with custom music?

### ISSUE THREAD

**Issue by FireHunterX** [Ivorforce/Psychedelicraft#18]
I tried to add music to the mod's .jar file. I get this when trying to launch the game.

---- Minecraft Crash Report ----
// Would you like a cupcake?

Time: 9/9/15 9:43 PM
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.ClassNotFoundException: ivorius.psychedelicraft.Psychedelicraft
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:544)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:208)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: ivorius.psychedelicraft.Psychedelicraft
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at cpw.mods.fml.common.ModClassLoader.loadClass(ModClassLoader.java:58)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:440)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:513)
	... 10 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 38 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Mac OS X (x86_64) version 10.10.4
	Java Version: 1.8.0_60, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 114408344 bytes (109 MB) / 301371392 bytes (287 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 5 total; -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1492 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UC	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UC	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1492-1.7.10.jar) 
	UC	Forge{10.13.4.1492} [Minecraft Forge] (forge-1.7.10-10.13.4.1492-1.7.10.jar) 
	UC	ivtoolkit{IvToolkit} [1.2] (minecraft.jar) 
	UE	psychedelicraft{1.5.2} [Psychedelicraft] (Psychedelicraft-1.5.2.jar) 
	GL info: ' Vendor: 'Intel' Version: '2.1 INTEL-10.6.31' Renderer: 'Intel(R) Iris(TM) Graphics 6100'

**Comment by FireHunterX** [comment]
I've realized that this is Forge not liking that the .jar was edited so it really has nothing to do with the custom music. How can I edit the jar without decompiling it so that Forge will still accept it?

**Comment by FireHunterX** [comment]
I've managed to get the music to work to some degree, but with issues.

For starters every time a world loads I hear all the custom sounds for a split second. This usually lets the world load but at times it freezes without crashing. All music was converted into .ogg files, but in the launcher's console log it reads this:
Thread-9/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:errorMessage:131]: Error in class 'CodecJOrbis'
[22:35:27] [Thread-9/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:errorMessage:132]:     File does not contain Vorbis header in method 'readHeader'.

And this:

[22:37:22] [Server thread/WARN]: Something's taking too long! 'root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root.root

Along with the standard lag messages and ticks skipped count.
And killing yourself after music has played will freeze the game when you try to respawn.

**Comment by Ivorforce** [comment]
I'm guessing your ogg file is broken / can't be read by Minecraft. Either way, it has nothing to do with Psychedelicraft per se - I don't really know much about how music loads in mc, sorry.
