### ISSUE TITLE
Possible conflict with agricraft? (AgriCraft v 1.4.1 and Psychedelicraft v 1.5.2)

### ISSUE THREAD

**Issue by MFernflower** [Ivorforce/Psychedelicraft#20]
java.lang.ArrayIndexOutOfBoundsException: 5
	at ivorius.psychedelicraft.blocks.BlockCoffea.func_149691_a(BlockCoffea.java:161)
	at com.InfinityRaider.AgriCraft.apiimpl.v1.cropplant.CropPlantTallGeneric.getPlantIcon(CropPlantTallGeneric.java:99)
	at com.InfinityRaider.AgriCraft.apiimpl.v1.cropplant.CropPlantTall.renderPlantInCrop(CropPlantTall.java:42)
	at com.InfinityRaider.AgriCraft.renderers.blocks.RenderCrop.doWorldRender(RenderCrop.java:47)
	at com.InfinityRaider.AgriCraft.renderers.blocks.RenderBlockBase.renderBlock(RenderBlockBase.java:80)
	at com.InfinityRaider.AgriCraft.renderers.blocks.RenderBlockBase.renderWorldBlock(RenderBlockBase.java:105)
	at cpw.mods.fml.client.registry.RenderingRegistry.renderWorldBlock(RenderingRegistry.java:118)
	at FMLRenderAccessLibrary.renderWorldBlock(FMLRenderAccessLibrary.java:53)
	at net.minecraft.client.renderer.RenderBlocks.func_147805_b(RenderBlocks.java:296)
	at net.minecraft.client.renderer.WorldRenderer.func_147892_a(WorldRenderer.java:181)
	at fastcraft.a.o.a(F:101)
	at fastcraft.Hooks.t(F:147)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1187)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1015)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:394)
	at org.multimc.EntryPoint.listen(EntryPoint.java:170)
	at org.multimc.EntryPoint.main(EntryPoint.java:54)

**Comment by MFernflower** [comment]
Happened after I planted coffee plants in a agricraft crop

**Comment by MFernflower** [comment]
Thank you
