### ISSUE TITLE
Random Crash on modpack

### ISSUE THREAD

**Issue by blockaxe333** [Ivorforce/Psychedelicraft#32]
Im trying to join either my SP world or this modpacks server, i get a crash stating the following : it results in a full client crash. 

---- Minecraft Crash Report ----
// There are four lights!

Time: 2/23/18 7:27 PM
Description: Ticking entity

java.lang.NoSuchMethodError: net.minecraft.world.World.func_82732_R()Lnet/minecraft/util/Vec3Pool;
	at ivorius.psychedelicraft.client.rendering.EffectLensFlare.updateLensFlares(EffectLensFlare.java:43)
	at ivorius.psychedelicraft.client.rendering.DrugRenderer.update(DrugRenderer.java:81)
	at ivorius.psychedelicraft.entities.DrugHelper.updateDrugEffects(DrugHelper.java:416)
	at ivorius.psychedelicraft.PSEventHandler.onPlayerTick(PSEventHandler.java:65)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_280_PSEventHandler_onPlayerTick_PlayerTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at cpw.mods.fml.common.FMLCommonHandler.onPlayerPostTick(FMLCommonHandler.java:350)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:353)
	at net.minecraft.client.entity.EntityClientPlayerMP.func_70071_h_(SourceFile:63)
	at net.minecraft.world.World.func_72866_a(World.java:2070)
	at net.minecraft.world.World.func_72870_g(World.java:2034)
	at net.minecraft.world.World.func_72939_s(World.java:1887)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2006)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by blockaxe333** [comment]
@Ivorforce
